/* Kiro Docs — visual-first for designers */

let DATA = null;
let currentPage = 'overview';
let currentView = 'designer';

async function boot() {
  try {
    const res = await fetch('./data.json');
    DATA = await res.json();
  } catch {
    DATA = getPlaceholderData();
  }
  initTheme();
  initView();
  renderSidebar();
  navigate('overview');
  updateHeader();
}

function updateHeader() {
  const p = document.getElementById('project-name');
  const b = document.getElementById('framework-badge');
  if (DATA.project) p.textContent = DATA.project;
  if (DATA.framework) b.textContent = DATA.framework;
}

/* ─── View toggle ────────────────────────────────── */
function initView() {
  const saved = localStorage.getItem('kiro-view') || 'designer';
  setView(saved, true);
}
function setView(view, silent) {
  currentView = view;
  localStorage.setItem('kiro-view', view);
  document.body.dataset.view = view;
  document.querySelectorAll('.view-btn').forEach(b => b.classList.toggle('active', b.dataset.view === view));
  if (!silent) navigate(currentPage);
}

/* ─── Theme ─────────────────────────────────────── */
function initTheme() {
  const saved = localStorage.getItem('kiro-theme');
  const isDark = saved ? saved === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches;
  if (isDark) document.documentElement.setAttribute('data-theme', 'dark');
  updateThemeToggle(isDark);
}
function toggleTheme() {
  const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
  if (isDark) { document.documentElement.removeAttribute('data-theme'); localStorage.setItem('kiro-theme', 'light'); }
  else { document.documentElement.setAttribute('data-theme', 'dark'); localStorage.setItem('kiro-theme', 'dark'); }
  updateThemeToggle(!isDark);
}
function updateThemeToggle(isDark) {
  const btn = document.getElementById('theme-toggle');
  btn.textContent = isDark ? '○' : '●';
}
document.getElementById('theme-toggle').addEventListener('click', toggleTheme);

/* ─── Sidebar ────────────────────────────────────── */
function renderSidebar() {
  const nav = document.getElementById('component-nav');
  const tc = document.getElementById('token-count');
  tc.textContent = Object.keys(DATA.tokens?.colors || {}).length || '—';
  if (!DATA.components?.length) { nav.innerHTML = '<div class="sidebar-item" style="pointer-events:none;opacity:.4">No components</div>'; return; }

  const categories = [
    { key: 'atom',     label: 'Atoms' },
    { key: 'molecule', label: 'Molecules' },
    { key: 'organism', label: 'Organisms' },
  ];

  const grouped = {};
  DATA.components.forEach(c => {
    const cat = c.category || 'atom';
    if (!grouped[cat]) grouped[cat] = [];
    grouped[cat].push(c);
  });

  nav.innerHTML = categories
    .filter(cat => grouped[cat.key]?.length)
    .map(cat => `
      <div class="sidebar-category-label">${cat.label}</div>
      ${grouped[cat.key].map(c => `
        <button class="sidebar-item" onclick="navigate('component:${c.slug}')" data-page="component:${c.slug}">
          ${c.name}
          <span class="sidebar-item-count">${c.variants?.length || 1}</span>
        </button>`).join('')}
    `).join('');
}

/* ─── Navigation ─────────────────────────────────── */
function navigate(page) {
  currentPage = page;
  document.querySelectorAll('.sidebar-item').forEach(el => el.classList.toggle('active', el.dataset.page === page));
  const content = document.getElementById('page-content');
  if (page === 'overview') content.innerHTML = renderOverview();
  else if (page === 'tokens') content.innerHTML = renderTokens();
  else if (page.startsWith('component:')) content.innerHTML = renderComponent(page.replace('component:', ''));
  if (window.Prism) Prism.highlightAll();
  window.scrollTo(0, 0);
}

/* ─── Overview ───────────────────────────────────── */
function renderOverview() {
  const cc = DATA.components?.length || 0;
  const colors = Object.keys(DATA.tokens?.colors || {}).length;
  const date = DATA.generatedAt ? new Date(DATA.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : '—';

  const cards = (DATA.components || []).map(c => `
    <a class="component-card" href="#" onclick="navigate('component:${c.slug}');return false;">
      <div class="component-card-thumb">
        ${renderMiniPreview(c)}
      </div>
      <div class="component-card-body">
        <div class="component-card-name">${c.name}</div>
        <div class="component-card-meta">${c.variants?.length || 1} variant${(c.variants?.length || 1) !== 1 ? 's' : ''}</div>
      </div>
    </a>`).join('');

  return `
    <div class="page">
      <div class="page-header">
        <div class="page-eyebrow">Design System</div>
        <h1 class="page-title">${DATA.project || 'Kiro Output'}</h1>
        <p class="page-description">Generated by Kiro · ${date}</p>
      </div>
      <div class="stats-row">
        <div class="stat"><div class="stat-value">${cc}</div><div class="stat-label">Components</div></div>
        <div class="stat"><div class="stat-value">${colors}</div><div class="stat-label">Color tokens</div></div>
        <div class="stat"><div class="stat-value">${Object.keys(DATA.tokens?.spacing || {}).length}</div><div class="stat-label">Spacing steps</div></div>
      </div>
      <div class="section">
        <div class="section-title">Components</div>
        ${cards ? `<div class="component-grid">${cards}</div>` : '<p class="muted">No components yet. Run /figma-to-code to generate.</p>'}
      </div>
    </div>`;
}

/* ─── Component page — VISUAL FIRST ─────────────── */
function renderComponent(slug) {
  const c = DATA.components?.find(c => c.slug === slug);
  if (!c) return `<div class="empty-state"><div class="empty-state-title">Component not found</div></div>`;

  const gallery = renderVariantGallery(c);
  const propsTable = renderPropsTable(c);
  const usage = generateUsageCode(c);

  return `
    <div class="page">
      <div class="page-header">
        <div class="page-eyebrow">Component</div>
        <h1 class="page-title">${c.name}</h1>
        <p class="page-description">${c.description || ''}</p>
      </div>

      <!-- VISUAL GALLERY — primary section -->
      <div class="section">
        <div class="section-title-row">
          <div class="section-title">Variants</div>
          <div class="bg-switcher" id="bg-switcher-${slug}">
            <button class="bg-btn active" onclick="setBg('${slug}','light-mesh')" title="Light mesh">◑</button>
            <button class="bg-btn" onclick="setBg('${slug}','dark-mesh')" title="Dark mesh">●</button>
            <button class="bg-btn" onclick="setBg('${slug}','white')" title="White">○</button>
            <button class="bg-btn" onclick="setBg('${slug}','gray')" title="Gray">▪</button>
          </div>
        </div>
        <div class="variant-gallery" id="gallery-${slug}" data-bg="light-mesh">
          ${gallery}
        </div>
      </div>

      <!-- PROPS TABLE — dev only -->
      <div class="section dev-only">
        <div class="section-title">Props</div>
        ${propsTable}
      </div>

      <!-- CODE — dev only -->
      <div class="section dev-only">
        <div class="section-title">Usage</div>
        <div class="code-block">
          <div class="code-block-toolbar">
            <span class="code-block-lang">tsx</span>
            <button class="copy-btn" onclick="copyCode(this)">copy</button>
          </div>
          <pre><code class="language-tsx">${escapeHtml(usage)}</code></pre>
        </div>
      </div>

      <!-- FIGMA META -->
      ${c.figmaId && c.figmaId !== '—' ? `
      <div class="section">
        <div class="section-title">Figma</div>
        <table class="props-table">
          <tbody>
            <tr><td><span class="prop-name">Node ID</span></td><td><span class="prop-type">${c.figmaId}</span></td></tr>
            <tr><td><span class="prop-name">Extracted</span></td><td><span class="prop-default">${DATA.generatedAt ? new Date(DATA.generatedAt).toLocaleDateString() : '—'}</span></td></tr>
          </tbody>
        </table>
      </div>` : ''}
    </div>`;
}

/* ─── Variant gallery renderer ───────────────────── */
function renderVariantGallery(c) {
  const renders = COMPONENT_RENDERS[c.slug];
  if (renders) return renders();

  // Generic fallback: show variant chips
  return `<div class="gallery-row">
    ${(c.variants || ['default']).map(v => `
      <div class="gallery-item">
        <div class="gallery-item-preview generic-preview">${c.name}</div>
        <div class="gallery-item-label">${v}</div>
      </div>`).join('')}
  </div>`;
}

/* ─── Per-component HTML renders ─────────────────── */
const COMPONENT_RENDERS = {

  'button': () => `
    <div class="gallery-label-row"><span class="gallery-row-label">Primary</span></div>
    <div class="gallery-row">
      ${['sm','md','lg'].map(s => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-preview btn-primary btn-${s}">Button</button></div>
          <div class="gallery-item-label">${s}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Secondary</span></div>
    <div class="gallery-row">
      ${['sm','md','lg'].map(s => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-preview btn-secondary btn-${s}">Button</button></div>
          <div class="gallery-item-label">${s}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Outline</span></div>
    <div class="gallery-row">
      ${['sm','md','lg'].map(s => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-preview btn-outline btn-${s}">Button</button></div>
          <div class="gallery-item-label">${s}</div>
        </div>`).join('')}
    </div>`,

  'button-shiny': () => `
    <div class="gallery-label-row"><span class="gallery-row-label">Light · Glass</span></div>
    <div class="gallery-row">
      ${['sm','md','lg','xl'].map((s,i) => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-shiny btn-shiny-light-glass btn-shiny-${s}">Shiny <span class="btn-chevron">›</span></button></div>
          <div class="gallery-item-label">${['Small','Medium','Large','Extra Large'][i]}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Dark · Glass</span></div>
    <div class="gallery-row">
      ${['sm','md','lg','xl'].map((s,i) => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-shiny btn-shiny-dark-glass btn-shiny-${s}">Shiny <span class="btn-chevron">›</span></button></div>
          <div class="gallery-item-label">${['Small','Medium','Large','Extra Large'][i]}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Light · Outline</span></div>
    <div class="gallery-row">
      ${['sm','md','lg','xl'].map((s,i) => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-shiny btn-shiny-light-outline btn-shiny-${s}">Shiny <span class="btn-chevron">›</span></button></div>
          <div class="gallery-item-label">${['Small','Medium','Large','Extra Large'][i]}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Light · Flat</span></div>
    <div class="gallery-row">
      ${['sm','md','lg','xl'].map((s,i) => `
        <div class="gallery-item">
          <div class="gallery-item-preview"><button class="btn-shiny btn-shiny-light-flat btn-shiny-${s}">Shiny <span class="btn-chevron">›</span></button></div>
          <div class="gallery-item-label">${['Small','Medium','Large','Extra Large'][i]}</div>
        </div>`).join('')}
    </div>`,

  'button-logo': () => {
    const sizes = [['sm','28px'],['md','32px'],['lg','36px'],['xl','44px']];
    const rows = [
      ['Light · Glass',   'light-glass'],
      ['Dark · Glass',    'dark-glass'],
      ['Light · Outline', 'light-outline'],
      ['Light · Flat',    'light-flat'],
    ];
    const figmaLogo = `<svg viewBox="0 0 16 16" fill="none" style="width:40%;height:40%">
      <path d="M5.5 2H8v3.5H5.5A1.75 1.75 0 1 1 5.5 2Z" fill="#F24E1E"/>
      <path d="M8 2h2.5a1.75 1.75 0 1 1 0 3.5H8V2Z" fill="#FF7262"/>
      <path d="M8 5.5h2.5a1.75 1.75 0 1 1 0 3.5H8V5.5Z" fill="#A259FF"/>
      <path d="M5.5 5.5H8V9H5.5A1.75 1.75 0 1 1 5.5 5.5Z" fill="#0ACF83"/>
      <circle cx="9.75" cy="10.75" r="1.75" fill="#1ABCFE"/>
    </svg>`;
    return rows.map(([label, cls]) => `
      <div class="gallery-label-row"><span class="gallery-row-label">${label}</span></div>
      <div class="gallery-row">
        ${sizes.map(([s, w]) => `
          <div class="gallery-item">
            <div class="gallery-item-preview">
              <button class="btn-logo btn-logo-${s} btn-logo-${cls}">${figmaLogo}</button>
            </div>
            <div class="gallery-item-label">${w}</div>
          </div>`).join('')}
      </div>`).join('');
  },

  'button-menu': () => {
    const userIcon = `<svg viewBox="0 0 14 14" fill="none" class="btn-menu-icon"><circle cx="7" cy="5" r="2.2" stroke="currentColor" stroke-width="1.4"/><path d="M2 12c0-2.2 2.2-4 5-4s5 1.8 5 4" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg>`;
    const lightItems = [
      ['Normal',   'btn-menu-light',          ''],
      ['Hover',    'btn-menu-light',          ''],
      ['Selected', 'btn-menu-selected-light', '<span class="btn-menu-glow btn-menu-glow-light"></span>'],
    ];
    const darkItems = [
      ['Normal',   'btn-menu-dark',          ''],
      ['Selected', 'btn-menu-selected-dark', '<span class="btn-menu-glow btn-menu-glow-dark"></span>'],
    ];
    return `
      <div class="gallery-label-row"><span class="gallery-row-label">Light</span></div>
      <div class="gallery-row" style="flex-direction:column;gap:2px;padding:1rem 1.25rem">
        <div class="btn-menu-wrap">
          ${lightItems.map(([label, cls, glow]) => `
            <button class="btn-menu ${cls}">${glow}${userIcon}${label}${userIcon}</button>`).join('')}
        </div>
      </div>
      <div class="gallery-label-row"><span class="gallery-row-label">Dark</span></div>
      <div class="gallery-row" style="flex-direction:column;gap:2px;padding:1rem 1.25rem">
        <div class="btn-menu-wrap">
          ${darkItems.map(([label, cls, glow]) => `
            <button class="btn-menu ${cls}">${glow}${userIcon}${label}${userIcon}</button>`).join('')}
        </div>
      </div>`;
  },

  'button-check': () => `
    <div class="gallery-label-row"><span class="gallery-row-label">Light</span></div>
    <div class="gallery-row">
      ${['glass','outline','flat'].map(style => `
        <div class="gallery-item">
          <div class="gallery-item-preview">
            <div class="btn-check-wrap">
              <div class="btn-check btn-check-light-${style}"><div class="btn-check-line"></div></div>
              <span class="btn-check-text">50 components</span>
            </div>
          </div>
          <div class="gallery-item-label">${style}</div>
        </div>`).join('')}
    </div>
    <div class="gallery-label-row"><span class="gallery-row-label">Dark</span></div>
    <div class="gallery-row">
      <div class="gallery-item">
        <div class="gallery-item-preview">
          <div class="btn-check-wrap">
            <div class="btn-check btn-check-dark"><div class="btn-check-line btn-check-line-dark"></div></div>
            <span class="btn-check-text btn-check-text-dark">50 components</span>
          </div>
        </div>
        <div class="gallery-item-label">glass</div>
      </div>
    </div>`,

  'card': () => `
    <div class="gallery-label-row"><span class="gallery-row-label">Variants</span></div>
    <div class="gallery-row">
      ${[['default','Default'],['bordered','Bordered'],['elevated','Elevated']].map(([v,l]) => `
        <div class="gallery-item">
          <div class="gallery-item-preview">
            <div class="card-preview card-preview-${v}">
              <div class="card-preview-header">Title</div>
              <div class="card-preview-body">Content</div>
            </div>
          </div>
          <div class="gallery-item-label">${l}</div>
        </div>`).join('')}
    </div>`,

  'input': () => `
    <div class="gallery-label-row"><span class="gallery-row-label">States</span></div>
    <div class="gallery-row gallery-row-col">
      <div class="gallery-item gallery-item-wide">
        <div class="gallery-item-preview gallery-item-preview-pad">
          <div class="input-preview-wrap">
            <label class="input-label">Default</label>
            <input class="input-preview" type="text" placeholder="Placeholder text" />
          </div>
        </div>
        <div class="gallery-item-label">Default</div>
      </div>
      <div class="gallery-item gallery-item-wide">
        <div class="gallery-item-preview gallery-item-preview-pad">
          <div class="input-preview-wrap">
            <label class="input-label">With error</label>
            <input class="input-preview input-preview-error" type="text" value="bad@" />
            <span class="input-error-msg">Invalid email address</span>
          </div>
        </div>
        <div class="gallery-item-label">Error</div>
      </div>
    </div>`,
};

/* ─── Background switcher ────────────────────────── */
function setBg(slug, bg) {
  const gallery = document.getElementById(`gallery-${slug}`);
  const switcher = document.getElementById(`bg-switcher-${slug}`);
  if (!gallery) return;
  gallery.dataset.bg = bg;
  switcher.querySelectorAll('.bg-btn').forEach(b => b.classList.remove('active'));
  event.target.classList.add('active');
}

/* ─── Mini preview for component cards ──────────── */
function renderMiniPreview(c) {
  const mini = MINI_PREVIEWS[c.slug];
  return mini ? mini() : `<span style="font-family:monospace;font-size:11px;opacity:.4">${c.name[0]}</span>`;
}

const MINI_PREVIEWS = {
  'button': () => `<button class="btn-preview btn-primary btn-md" style="pointer-events:none">Button</button>`,
  'button-shiny': () => `<button class="btn-shiny btn-shiny-light-glass btn-shiny-md" style="pointer-events:none">Shiny ›</button>`,
  'button-logo': () => `<button class="btn-logo btn-logo-md btn-logo-light-glass" style="pointer-events:none"><svg viewBox="0 0 16 16" fill="none" style="width:40%;height:40%"><path d="M5.5 2H8v3.5H5.5A1.75 1.75 0 1 1 5.5 2Z" fill="#F24E1E"/><path d="M8 2h2.5a1.75 1.75 0 1 1 0 3.5H8V2Z" fill="#FF7262"/><path d="M8 5.5h2.5a1.75 1.75 0 1 1 0 3.5H8V5.5Z" fill="#A259FF"/><path d="M5.5 5.5H8V9H5.5A1.75 1.75 0 1 1 5.5 5.5Z" fill="#0ACF83"/><circle cx="9.75" cy="10.75" r="1.75" fill="#1ABCFE"/></svg></button>`,
  'button-menu': () => `<button class="btn-menu btn-menu-selected-light" style="pointer-events:none;font-size:11px;padding:3px 8px"><span class="btn-menu-glow btn-menu-glow-light"></span>Account</button>`,
  'button-check': () => `<div class="btn-check btn-check-light-glass" style="pointer-events:none"><div class="btn-check-line"></div></div>`,
  'card': () => `<div class="card-preview card-preview-default" style="width:80px;pointer-events:none"><div class="card-preview-header" style="font-size:9px">Card</div></div>`,
  'input': () => `<input class="input-preview" style="width:100px;pointer-events:none" placeholder="Input" readonly />`,
};

/* ─── Props table ────────────────────────────────── */
function renderPropsTable(c) {
  if (!c.props?.length) return '<p class="muted">No props documented.</p>';
  return `<table class="props-table">
    <thead><tr><th>Prop</th><th>Type</th><th>Default</th><th>Description</th></tr></thead>
    <tbody>
      ${c.props.map(p => `
        <tr>
          <td><span class="prop-name">${p.name}</span>${p.required ? '<span class="prop-required">req</span>' : ''}</td>
          <td><span class="prop-type">${escapeHtml(p.type)}</span></td>
          <td><span class="prop-default">${p.default || '—'}</span></td>
          <td>${p.description || ''}</td>
        </tr>`).join('')}
    </tbody>
  </table>`;
}

/* ─── Tokens page ────────────────────────────────── */
function renderTokens() {
  const colors = DATA.tokens?.colors || {};
  const typo = DATA.tokens?.typography || {};
  const spacing = DATA.tokens?.spacing || {};
  const effects = DATA.tokens?.effects || {};

  return `
    <div class="page">
      <div class="page-header">
        <div class="page-eyebrow">Foundation</div>
        <h1 class="page-title">Design Tokens</h1>
        <p class="page-description">Variables extraídas del archivo Figma vía MCP. Úsalas como CSS custom properties.</p>
      </div>
      <div class="section">
        <div class="section-title">Colors</div>
        <div class="token-grid">
          ${Object.entries(colors).map(([k,v]) => `
            <div class="token-swatch">
              <div class="swatch-color" style="background:${v};${v.includes('rgba') || v.includes('99') || v.includes('80') ? 'background-image:linear-gradient(45deg,#ccc 25%,transparent 25%,transparent 75%,#ccc 75%,#ccc),linear-gradient(45deg,#ccc 25%,transparent 25%,transparent 75%,#ccc 75%,#ccc);background-size:8px 8px;background-position:0 0,4px 4px;' : ''}"></div>
              <div class="swatch-name">${k}</div>
              <div class="swatch-value">${v}</div>
            </div>`).join('')}
        </div>
      </div>
      <div class="section">
        <div class="section-title">Typography</div>
        <div class="type-scale">
          ${Object.entries(typo).map(([name,s]) => `
            <div class="type-row">
              <span class="type-label">${name}</span>
              <span class="type-sample" style="font-size:${s.size};font-weight:${s.weight};line-height:${s.lineHeight}">The quick brown fox</span>
            </div>`).join('')}
        </div>
      </div>
      ${Object.keys(effects).length ? `
      <div class="section">
        <div class="section-title">Effects</div>
        <div class="spacing-scale">
          ${Object.entries(effects).map(([k,v]) => `
            <div class="spacing-row" style="align-items:flex-start;flex-direction:column;gap:.25rem;padding:.75rem 0;border-bottom:1px solid var(--border)">
              <span class="spacing-label" style="min-width:auto;font-weight:600">${k}</span>
              <span class="spacing-value" style="font-size:11px;color:var(--text-muted)">${v}</span>
            </div>`).join('')}
        </div>
      </div>` : ''}
      <div class="section">
        <div class="section-title">Spacing &amp; Sizing</div>
        <div class="spacing-scale">
          ${Object.entries(spacing).map(([k,v]) => `
            <div class="spacing-row">
              <span class="spacing-label">${k}</span>
              <div class="spacing-bar" style="width:${Math.min(parseFloat(v)*4,300)}px"></div>
              <span class="spacing-value">${v}</span>
            </div>`).join('')}
        </div>
      </div>
    </div>`;
}

/* ─── Usage code generator ───────────────────────── */
function generateUsageCode(c) {
  const name = c.name;
  const fw = DATA.framework || 'react-tailwind';
  if (c.slug === 'button-shiny') {
    return `import { ButtonShiny } from './components/button-shiny';\n\n// Light glass (default)\n<ButtonShiny>Shiny</ButtonShiny>\n\n// Dark glass with glow\n<ButtonShiny mode="dark" showGlow>\n  Preview\n</ButtonShiny>\n\n// Outline\n<ButtonShiny style="outline">Shiny</ButtonShiny>`;
  }
  if (c.slug === 'button-check') {
    return `import { ButtonCheck } from './components/button-check';\n\n<ButtonCheck mode="light" style="glass" />\n<ButtonCheck mode="dark" />`;
  }
  return `import { ${name} } from './components/${c.slug}';\n\n<${name}>${name}</${name}>`;
}

/* ─── Helpers ────────────────────────────────────── */
function copyCode(btn) {
  const text = btn.closest('.code-block').querySelector('pre').textContent;
  navigator.clipboard.writeText(text).then(() => {
    btn.textContent = 'copied';
    btn.classList.add('copied');
    setTimeout(() => { btn.textContent = 'copy'; btn.classList.remove('copied'); }, 1500);
  });
}

function escapeHtml(s) {
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

/* ─── Placeholder data ───────────────────────────── */
function getPlaceholderData() {
  return {
    project: 'My Design System', framework: 'react-tailwind',
    generatedAt: new Date().toISOString(),
    components: [
      { name: 'Button', slug: 'button', description: 'Primary interactive element.', variants: ['primary','secondary','outline'],
        props: [{ name: 'variant', type: "'primary'|'secondary'|'outline'", default: "'primary'", description: 'Visual style' }] },
      { name: 'ButtonShiny', slug: 'button-shiny', description: 'Glass-morphism action button.', variants: ['glass','outline','flat'], figmaId: '159:7945',
        props: [{ name: 'mode', type: "'light'|'dark'", default: "'light'", description: 'Surface context' },
                { name: 'style', type: "'glass'|'outline'|'flat'", default: "'glass'", description: 'Style variant' },
                { name: 'showGlow', type: 'boolean', default: 'false', description: 'Rainbow glow' }] },
      { name: 'ButtonCheck', slug: 'button-check', description: 'Circular feature indicator.', variants: ['glass','outline','flat'], figmaId: '169:14283',
        props: [{ name: 'mode', type: "'light'|'dark'", default: "'light'", description: 'Surface context' }] },
      { name: 'Card', slug: 'card', description: 'Content surface.', variants: ['default','bordered','elevated'], props: [] },
      { name: 'Input', slug: 'input', description: 'Text input.', variants: ['default','error'], props: [] },
    ],
    tokens: {
      colors: { 'neutral-50': '#fafafa', 'neutral-200': '#e5e5e5', 'neutral-600': '#525252', 'neutral-900': '#171717' },
      typography: { heading: { size: '2rem', weight: 700, lineHeight: 1.2 }, body: { size: '1rem', weight: 400, lineHeight: 1.6 } },
      spacing: { '1': '0.25rem', '4': '1rem', '8': '2rem', '16': '4rem' },
    },
  };
}

boot();
